import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";
import { ece, fitLogReg, fitTemperature, lbfgs, pickThreshold, stratifiedSplit, trainStaticHead } from "../src/train";
import { softmax } from "../src/text";

// generated by Python (sklearn LogisticRegression + microdecide.calibrate) — see git history of M4.5
const fx = JSON.parse(readFileSync(resolve(__dirname, "fixtures/train_fixture.json"), "utf8"));
const X: Float64Array[] = fx.X.map((r: number[]) => Float64Array.from(r));

describe("lbfgs", () => {
  it("minimizes a quadratic", () => {
    const { x } = lbfgs((v, g) => {
      g[0] = 2 * (v[0] - 3);
      g[1] = 20 * (v[1] + 1);
      return (v[0] - 3) ** 2 + 10 * (v[1] + 1) ** 2;
    }, new Float64Array(2));
    expect(x[0]).toBeCloseTo(3, 5);
    expect(x[1]).toBeCloseTo(-1, 5);
  });
});

describe("logistic regression matches sklearn", () => {
  it("same folded head (coef/intercept) and predictions", () => {
    const report = trainStaticHead({ X, y: fx.y, labels: ["a", "b", "c"], weights: fx.w, split: fx.split, cGrid: [fx.C], targetPrecision: 0.9 });
    const coef = report.head.coef.flat();
    const sk = (fx.sk_coef as number[][]).flat();
    const maxDiff = Math.max(...coef.map((c, i) => Math.abs(c - sk[i])));
    expect(maxDiff).toBeLessThan(1e-3);
    report.head.intercept.forEach((b, k) => expect(b).toBeCloseTo(fx.sk_intercept[k], 3));
    const pred = X.map((v) => {
      const z = report.head.intercept.map((b, k) => b + report.head.coef[k].reduce((a, w, j) => a + w * v[j], 0));
      return z.indexOf(Math.max(...z));
    });
    expect(pred).toEqual(fx.sk_pred);
    expect(report.C).toBe(fx.C);
    expect(report.test.n).toBe(36);
  });

  it("fitLogReg warm start reaches the same optimum", () => {
    const Z = X.slice(0, 50);
    const y = fx.y.slice(0, 50);
    const s = new Array(50).fill(1);
    const cold = fitLogReg(Z, y, s, 3, 1);
    const warm = fitLogReg(Z, y, s, 3, 1, fitLogReg(Z, y, s, 3, 0.1));
    for (let i = 0; i < cold.length; i++) expect(warm[i]).toBeCloseTo(cold[i], 3);
  });
});

describe("calibration matches microdecide.calibrate", () => {
  const logits = (fx.val_logits as number[][]).map((r) => Float64Array.from(r));
  it("temperature", () => expect(fitTemperature(logits, fx.val_y)).toBeCloseTo(fx.temperature, 3));
  it("ece + threshold", () => {
    const probs = logits.map((z) => softmax(z, fx.temperature));
    expect(ece(probs, fx.val_y)).toBeCloseTo(fx.ece_after, 9);
    const conf = probs.map((p) => Math.max(...p));
    const correct = probs.map((p, i) => p.indexOf(Math.max(...p)) === fx.val_y[i]);
    const t = pickThreshold(conf, correct, 0.9);
    expect(t.reached).toBe(fx.threshold.reached);
    expect(t.threshold).toBeCloseTo(fx.threshold.threshold, 12);
    expect(t.coverage).toBeCloseTo(fx.threshold.coverage, 12);
  });
});

describe("stratifiedSplit", () => {
  it("is deterministic, stratified, and reaches every split for small labels", () => {
    const y = [...new Array(100).fill(0), ...new Array(40).fill(1), ...new Array(3).fill(2)];
    const a = stratifiedSplit(y, 1);
    expect(a).toEqual(stratifiedSplit(y, 1));
    expect(a).not.toEqual(stratifiedSplit(y, 2));
    const count = (label: number, s: string) => a.filter((v, i) => y[i] === label && v === s).length;
    expect(count(0, "test")).toBe(15);
    expect(count(0, "val")).toBe(15);
    expect(new Set(a.filter((_, i) => y[i] === 2))).toEqual(new Set(["train", "val", "test"]));
  });
});
